source "${stdenv}/setup"

installPhase() {
	STYLES=(LLVM GNU Google Chromium Microsoft Mozilla WebKit)
	HEADER="### generated by clang-format ${version}"

	mkdir -p "${out}"

	for style in "${STYLES[@]}"; do
		style_file="${out}/clang-format-${style@L}.yml"

		echo "${HEADER}" >"${style_file}"
		clang-format --style="${style}" --dump-config >>"${style_file}"
	done

	substituteAll "README.md" "${out}/README.md"
}

genericBuild
