#! /usr/bin/env bash

set -e

STYLES=(LLVM GNU Google Chromium Microsoft Mozilla WebKit)

cf_version=$(clang-format --version)
cf_header="### generated by $cf_version"

for style in "${STYLES[@]}"; do
	style_file="clang-format-${style@L}.yml"

	echo "$cf_header" >"$style_file"
	clang-format --style="$style" --dump-config >>"$style_file"
done
