#! /usr/bin/env nix-shell
#! nix-shell --pure -i bash -p clang-tools
#! nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/9bc841fec1c0e8b9772afa29f934d2c7ce57da8e.tar.gz

set -e

STYLES=(LLVM GNU Google Chromium Microsoft Mozilla WebKit)

cf_version=$(clang-format --version)
cf_header="### generated by $cf_version"

for style in "${STYLES[@]}"; do
	style_file="clang-format-${style@L}.yml"

	echo "$cf_header" >"$style_file"
	clang-format --style="$style" --dump-config >>"$style_file"
done
