name: build
on:
  push:
    branches: [source]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - run: nix build
      - use: actions/upload-artifact@v3
        with:
          path: result
