name: build
on:
  push:
    branches: [source]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - run: nix build
      - run: echo "UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: result
          path: ${{ env.UPLOAD_PATH }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/download-artifact@v3
        with:
          name: result
      - run: echo "VERSION=$(cat version)" >> $GITHUB_ENV
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: "update/${{ env.VERSION }}"
          commit-message: "update to clang-format v${{ env.VERSION }}"
          title: "[AUTO] Update to clang-format v${{ env.VERSION }}"
