name: update
on: 
  schedule:
    - cron: '0 0 * * *' # every day at 00:00
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-update: ${{ steps.check.outputs.needs-update }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: source
      - uses: cachix/install-nix-action@v17
      - run: nix flake update
      - run: nix build
      - run: curl -L 'https://raw.githubusercontent.com/jessestricker/clang-format-styles/main/version' > current-version
      - run: cp result/version ./latest-version
      - id: check
        run: |
          if diff current-version latest-version; then
            echo "::set-output name=needs-update::false"
          else
            echo "::set-output name=needs-update::true"
          fi
  update:
    needs: check
    if: ${{ needs.check.outputs.needs-update == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: source
      - uses: cachix/install-nix-action@v17
      - run: nix flake update --commit-lock-file
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: "nix-update"
          title: "[AUTO] Update Nix flake inputs"
